/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as privateIndexRouteImport } from "./routes/(private)/index"

const privateIndexRoute = privateIndexRouteImport.update({
  id: "/(private)/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof privateIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof privateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/(private)/": typeof privateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/"
  fileRoutesByTo: FileRoutesByTo
  to: "/"
  id: "__root__" | "/(private)/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateIndexRoute: typeof privateIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(private)/": {
      id: "/(private)/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof privateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  privateIndexRoute: privateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
