/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as defaultIndexRouteImport } from "./routes/(private)/index";
import { Route as rootRouteImport } from "./routes/__root";

const defaultIndexRoute = defaultIndexRouteImport.update({
  id: "/(private)/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof defaultIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof defaultIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(private)/": typeof defaultIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/";
  id: "__root__" | "/(private)/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  defaultIndexRoute: typeof defaultIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(private)/": {
      id: "/(private)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof defaultIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  defaultIndexRoute: defaultIndexRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
